default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30
  port: 5432

development:
  <<: *default
  database: mataio_dev

test:
  <<: *default
  database: martaio_test

production:
  <<: *default
  pool: 80
  url: <%= ENV['POSTGRESQL_URL'] %>
